# Copyright 2022 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/buildflag_header.gni")
import("//content/browser/ml/webnn/dml/features.gni")

buildflag_header("buildflags") {
  header = "buildflags.h"

  flags = [ "ENABLE_MOJO_WEBNN_IN_GPU_PROCESS=$build_webnn_with_directml" ]
}

source_set("lib") {
  sources = [
    "webnn_service_factory.cc",
    "webnn_service_factory.h",
  ]

  if (build_webnn_with_directml) {
    if (is_win) {
      sources += [
        "dml/adapter_dml.cc",
        "dml/adapter_dml.h",
        "dml/command_queue.cc",
        "dml/command_queue.h",
        "dml/command_recorder.cc",
        "dml/command_recorder.h",
        "dml/context_dml_impl.cc",
        "dml/context_dml_impl.h",
        "dml/execution_context.cc",
        "dml/execution_context.h",
        "dml/execution_resources.cc",
        "dml/execution_resources.h",
        "dml/gpgmm.cpp",
        "dml/gpgmm.h",
        "dml/gpgmm_d3d12.cpp",
        "dml/gpgmm_d3d12.h",
        "dml/graph_desc_builder.cc",
        "dml/graph_desc_builder.h",
        "dml/graph_dml_impl.cc",
        "dml/graph_dml_impl.h",
        "dml/graph_node_output.cc",
        "dml/graph_node_output.h",
        "dml/graph_tensor_desc.cc",
        "dml/graph_tensor_desc.h",
        "dml/mojo_server_dml_impl.cc",
        "dml/mojo_server_dml_impl.h",
        "dml/readback_resource.cc",
        "dml/readback_resource.h",
        "dml/upload_resource.cc",
        "dml/upload_resource.h",
        "dml/utils_dml.h",
        "dml/webnn_service_dml_impl.cc",
        "dml/webnn_service_dml_impl.h",
      ]

      libs = [
        "dxgi.lib",
        "d3d12.lib",
        "directml.lib",
      ]
    }
  } else {
    sources += [
      "mojo_server_impl.cc",
      "mojo_server_impl.h",
      "webnn_service_impl.cc",
      "webnn_service_impl.h",
    ]
  }

  deps = [
    "//base",
    "//components/ml/mojom",
    "//mojo/public/cpp/bindings",
  ]
}
